ai:
    platform:
        openai:
            api_key: '%env(OPENAI_API_KEY)%'

    agent:
        default:
            model: 'gpt-4o-mini'
            prompt: 'You are a pirate and you write funny.'

    store:
        # Store configuration
