ai:
    platform:
        openai:
            api_key: '%env(OPENAI_API_KEY)%'
    agent:
        youtube:
            model:
                class: 'Symfony\AI\Platform\Bridge\OpenAi\Gpt'
                name: 'gpt-4o-mini'
            tools: false
        phpdd:
            model:
                class: 'Symfony\AI\Platform\Bridge\OpenAi\Gpt'
                name: 'gpt-4o-mini'
            tools:
                - 'Symfony\AI\Agent\Toolbox\Tool\Clock'
            prompt: 'You are a helpful assistant for answering questions about the PHP Developer Days conference.'
            memory:
                service: 'App\PhpDd\ConferenceMemory'
        wikipedia:
            model:
                class: 'Symfony\AI\Platform\Bridge\OpenAi\Gpt'
                name: 'gpt-4o-mini'
            tools:
                - 'Symfony\AI\Agent\Toolbox\Tool\Wikipedia'
            prompt: |
                You are a helpful assistant for answering the users questions based on Wikipedia articles.
                Please provide the link to an article for further reading.
        blog:
            model:
                class: 'Symfony\AI\Platform\Bridge\OpenAi\Gpt'
                name: 'gpt-4o-mini'
            tools:
                - 'Symfony\AI\Agent\Toolbox\Tool\Clock'
                - 'Symfony\AI\Agent\Toolbox\Tool\SimilaritySearch'
            prompt: |
                You are a helpful assistant for answering the users questions based on Symfony blog articles.
                If you don't know the answer, just say "I don't know".
                Please provide the link to the article for further reading.
    store:
        chroma_db:
            symfonycon:
                collection: 'symfony_blog'
    vectorizer:
        openai:
            model:
                class: 'Symfony\AI\Platform\Bridge\OpenAi\Embeddings'
                name: !php/const Symfony\AI\Platform\Bridge\OpenAi\Embeddings::TEXT_ADA_002
    indexer:
        blog:
            loader: 'App\Blog\FeedLoader'
            source: 'https://feeds.feedburner.com/symfony/blog'
            transformers:
                - 'Symfony\AI\Store\Document\Transformer\TextTrimTransformer'
            vectorizer: 'ai.vectorizer.openai'
            store: 'ai.store.chroma_db.symfonycon'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\AI\Agent\Toolbox\Tool\Clock:
        $timezone: 'Europe/Berlin'
    Symfony\AI\Agent\Toolbox\Tool\Wikipedia: ~
    Symfony\AI\Agent\Toolbox\Tool\SimilaritySearch:
        $vectorizer: '@ai.vectorizer.openai'
        $store: '@ai.store.chroma_db.symfonycon'

    Symfony\AI\Store\Document\Transformer\TextTrimTransformer: ~
